"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EnrollmentStatus = void 0;
var EnrollmentStatus;
(function (EnrollmentStatus) {
    EnrollmentStatus["AWAITING_CONSENT"] = "Awaiting Consent";
    EnrollmentStatus["CONSENT_EXPIRED"] = "Consent Expired";
    EnrollmentStatus["CONSENT_INACTIVE"] = "Consent Inactive";
    EnrollmentStatus["ENROLLED"] = "Enrolled";
})(EnrollmentStatus = exports.EnrollmentStatus || (exports.EnrollmentStatus = {}));
class Constants {
}
exports.default = Constants;
Constants.EPIC_PATIENT = 'e';
Constants.BP3_PATIENT = 'BAA';
// public static AUTHORIZATION = 'Authorization';
Constants.authorization = 'authorization';
Constants.AUTHORIZATION = 'x-forwarded-authorization';
Constants.R4_EPIC_URL = 'https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/';
Constants.BUNDLE = 'Bundle';
Constants.SUMMARY = 'SUMMARY';
Constants.DETAILED = 'DETAILED';
Constants.LOOK_BACK = 10;
Constants.responseTypeDB = 'DB';
Constants.responseTypeEMR = 'EMR';
Constants.requestTypePOST = 'POST';
Constants.NO_DATA_FOUND = 'NoResults';
Constants.NO_DATA_FOUND_DESC = 'Results not found';
Constants.BAD_REQUEST = 'Bad request, Invalid records';
Constants.ACTIVE = 'ACTIVE';
Constants.CONSENT_ENROLMENT = 'ENROLMENT';
Constants.TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS';
Constants.REMOVE_PATIENT_RECORD_FROM_TABLES = ['questionnaire_response', 'patient_device_details', 'enrollment', 'patient', 'patient_activity', 'careplan', 'patient_plandefinition'];
Constants.PROCEDURE_SYSTEM_CODE = ['CPT4', 'ICD10PCS'];
Constants.DIAGNOSIS_SYSTEM_CODE = ['ICD10CM'];
Constants.ICD10_CODE_TYPE = ['procedure', 'diagnosis'];
Constants.MEDICATION_LOOKBACK = 2;
Constants.ENTRY = 'entry';
Constants.BIRTH_DATE = 'birthDate';
Constants.EMAIL = 'email';
Constants.EPIC_RESOURCE = 'epicResource';
Constants.EPIC_TYPE = 'epicType';
Constants.FHIR_ID = 'fhirId';
Constants.GENDER = 'gender';
Constants.INVIATATION_STATUS = 'invitationStatus';
Constants.META = 'meta';
Constants.NAME = 'name';
Constants.RESOURCE_TYPE = 'resourceType';
Constants.STATUS = 'status';
Constants.TELECOM = 'telecom';
Constants.GET = 'get';
Constants.ISO_8601_MS_FMT = "%Y-%m-%dT%H:%M:%SZ";
Constants.ID = 'id';
Constants.CREATED = 'created';
Constants.UPDATED = 'updated';
Constants.VERSION_ID = 'versionId';
Constants.EPIC_FORMAT = 'epic-format';
Constants.DSTU2 = 'DSTU2';
Constants.R4 = 'R4';
Constants.COUNT = 'count';
Constants.ENROLLMENT_STATUS = 'enrollmentStatus';
Constants.PATIENT_ID = 'patientId';
Constants.EPIC_RESOURCES = 'epicResources';
Constants.FAMILY = 'family';
Constants.GIVEN = 'given';
Constants.BIRTHDATE = 'birthdate';
Constants.V1 = 'v1';
Constants.PATIENT_FHIR_ID = 'patientFHIRId';
//# sourceMappingURL=constant.js.map